#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/name4ef/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# Start DBUS session bus:
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
   eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

if [ `hostname` = "dev1" ]; then
	#xrandr --output HDMI-0 --left-of DVI-I-1
	#synergy &
	#DISPLAY=:0.1 gkrellm &
	echo 1 > /dev/null

elif [ `hostname` = "xor" ]; then
	xrandr --output LVDS1 --off --output VGA1 --mode 1024x768

fi

setxkbmap -layout us,ru -option grp:shift_toggle &
#dropboxd &
xscreensaver -nosplash &

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/name4ef/.fluxbox/log"
